- ros_topic_name: "/lidar_3d/points"
  gz_topic_name: "/world/tugbot_depot/model/x500_lidar_3d_0/link/link/sensor/lidar_3d/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
 
- ros_topic_name: "/lidar_3d/scan"
  gz_topic_name: "/world/tugbot_depot/model/x500_lidar_3d_0/link/link/sensor/lidar_3d/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu"
  gz_topic_name: "/world/tugbot_depot/model/x500_lidar_3d_0/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS